export default [
  // electronic devices
  {
    name: "RAM",
    filterType: "MULTIPLE_SELECT",
    subCategoryName: "Smartphones",
    categoryName: "Electronic Devices",
    categoryId: 1,
    value: null,
    productId: null,
  },
  {
    name: "RAM",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Electronic Devices",
    subCategoryName: "Laptops",
    categoryId: 1,
    value: null,
    productId: null,
  },
  {
    name: "RAM",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Electronic Devices",
    subCategoryName: "Consoles",
    categoryId: 1,
    value: null,
    productId: null,
  },
  {
    name: "Brand",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Electronic Devices",
    subCategoryName: "Consoles",
    categoryId: 1,
    value: null,
    productId: null,
  },
  {
    name: "Brand",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Electronic Devices",
    subCategoryName: "Laptops",
    categoryId: 1,
    value: null,
    productId: null,
  },
  {
    name: "Brand",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Electronic Devices",
    subCategoryName: "Smartphones",
    categoryId: 1,
    value: null,
    productId: null,
  },
  {
    name: "Storage",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Electronic Devices",
    subCategoryName: "Laptops",
    categoryId: 1,
    value: null,
    productId: null,
  },
  {
    name: "Storage",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Electronic Devices",
    subCategoryName: "Smartphones",
    categoryId: 1,
    value: null,
    productId: null,
  },
  {
    name: "Storage",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Electronic Devices",
    subCategoryName: "Consoles",
    categoryId: 1,
    value: null,
    productId: null,
  },
  {
    name: "Graphics Card",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Electronic Devices",
    subCategoryName: "Smartphones",
    categoryId: 1,
    value: null,
    productId: null,
  },
  {
    name: "Graphics Card",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Electronic Devices",
    subCategoryName: "Laptops",
    categoryId: 1,
    value: null,
    productId: null,
  },
  {
    name: "Graphics Card",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Electronic Devices",
    subCategoryName: "Consoles",
    categoryId: 1,
    value: null,
    productId: null,
  },
  {
    name: "Warranty",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Electronic Devices",
    subCategoryName: "Smartphones",
    categoryId: 1,
    value: null,
    productId: null,
  },
  {
    name: "Warranty",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Electronic Devices",
    subCategoryName: "Laptops",
    categoryId: 1,
    value: null,
    productId: null,
  },
  {
    name: "Warranty",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Electronic Devices",
    subCategoryName: "Consoles",
    categoryId: 1,
    value: null,
    productId: null,
  },

  // electronic accessories
  {
    name: "Color",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Electronic Accessories",
    subCategoryName: "Headphones",
    categoryId: 2,
    value: null,
    productId: null,
  },
  {
    name: "Color",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Electronic Accessories",
    subCategoryName: "Keyboard and Mouse",
    categoryId: 2,
    value: null,
    productId: null,
  },
  {
    name: "Color",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Electronic Accessories",
    subCategoryName: "Speakers",
    categoryId: 2,
    value: null,
    productId: null,
  },
  {
    name: "Guarantee",
    filterType: "SINGLE_SELECT",
    categoryName: "Electronic Accessories",
    subCategoryName: "Speakers",
    categoryId: 2,
    value: null,
    productId: null,
  },
  {
    name: "Guarantee",
    filterType: "SINGLE_SELECT",
    categoryName: "Electronic Accessories",
    subCategoryName: "Keyboard and Mouse",
    categoryId: 2,
    value: null,
    productId: null,
  },
  {
    name: "Guarantee",
    filterType: "SINGLE_SELECT",
    categoryName: "Electronic Accessories",
    subCategoryName: "Headphones",
    categoryId: 2,
    value: null,
    productId: null,
  },

  {
    name: "Brand",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Electronic Accessories",
    subCategoryName: "Headphones",
    categoryId: 2,
    value: null,
    productId: null,
  },
  {
    name: "Brand",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Electronic Accessories",
    subCategoryName: "Speakers",
    categoryId: 2,
    value: null,
    productId: null,
  },
  {
    name: "Brand",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Electronic Accessories",
    subCategoryName: "Keyboard and Mouse",
    categoryId: 2,
    value: null,
    productId: null,
  },

  // tv & home appliances
  {
    name: "Color",
    filterType: "MULTIPLE_SELECT",
    categoryName: "TV & Home Appliances",
    subCategoryName: "Televisions",
    categoryId: 3,
    value: null,
    productId: null,
  },
  {
    name: "Color",
    filterType: "MULTIPLE_SELECT",
    categoryName: "TV & Home Appliances",
    subCategoryName: "Washing Machine",
    categoryId: 3,
    value: null,
    productId: null,
  },
  {
    name: "Color",
    filterType: "MULTIPLE_SELECT",
    categoryName: "TV & Home Appliances",
    subCategoryName: "Refrigerator",
    categoryId: 3,
    value: null,
    productId: null,
  },
  {
    name: "Brand",
    filterType: "MULTIPLE_SELECT",
    categoryName: "TV & Home Appliances",
    subCategoryName: "Refrigerator",
    categoryId: 3,
    value: null,
    productId: null,
  },
  {
    name: "Brand",
    filterType: "MULTIPLE_SELECT",
    categoryName: "TV & Home Appliances",
    subCategoryName: "Washing Machine",
    categoryId: 3,
    value: null,
    productId: null,
  },
  {
    name: "Brand",
    filterType: "MULTIPLE_SELECT",
    categoryName: "TV & Home Appliances",
    subCategoryName: "Televisions",
    categoryId: 3,
    value: null,
    productId: null,
  },
  {
    name: "Size",
    filterType: "SINGLE_SELECT",
    categoryName: "TV & Home Appliances",
    subCategoryName: "Washing Machine",
    categoryId: 3,
    value: null,
    productId: null,
  },
  {
    name: "Size",
    filterType: "SINGLE_SELECT",
    categoryName: "TV & Home Appliances",
    subCategoryName: "Televisions",
    categoryId: 3,
    value: null,
    productId: null,
  },
  {
    name: "Size",
    filterType: "SINGLE_SELECT",
    categoryName: "TV & Home Appliances",
    subCategoryName: "Refrigerator",
    categoryId: 3,
    value: null,
    productId: null,
  },

  // Health & Beauty
  {
    name: "Brand",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Health & Beauty",
    subCategoryName: "Lotions",
    value: null,
    productId: null,
  },
  {
    name: "Brand",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Health & Beauty",
    subCategoryName: "Oil",
    value: null,
    productId: null,
  },
  {
    name: "Brand",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Treadmill",
    subCategoryName: "Oil",
    value: null,
    productId: null,
  },
  {
    name: "Brand",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Treadmill",
    subCategoryName: "Gym Equipments",
    value: null,
    productId: null,
  },

  // Women's Fashion
  {
    name: "Brand",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Women's Fashion",
    subCategoryName: "Skirts",
    categoryId: 5,
    value: null,
    productId: null,
  },
  {
    name: "Brand",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Women's Fashion",
    subCategoryName: "One Piece",
    categoryId: 5,
    value: null,
    productId: null,
  },
  {
    name: "Brand",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Women's Fashion",
    subCategoryName: "Watches",
    categoryId: 5,
    value: null,
    productId: null,
  },
  {
    name: "Color",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Men's Fashion",
    subCategoryName: "Watches",
    categoryId: 5,
    value: null,
    productId: null,
  },
  {
    name: "Color",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Men's Fashion",
    subCategoryName: "Skirts",
    categoryId: 5,
    value: null,
    productId: null,
  },
  {
    name: "Color",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Men's Fashion",
    subCategoryName: "One Piece",
    categoryId: 5,
    value: null,
    productId: null,
  },

  // Men's Fashion
  {
    name: "Brand",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Men's Fashion",
    subCategoryName: "Smart Watches",
    categoryId: 6,
    value: null,
    productId: null,
  },
  {
    name: "Brand",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Men's Fashion",
    subCategoryName: "Pants",
    categoryId: 6,
    value: null,
    productId: null,
  },
  {
    name: "Brand",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Men's Fashion",
    subCategoryName: "Jackets",
    categoryId: 6,
    value: null,
    productId: null,
  },
  {
    name: "Color",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Men's Fashion",
    subCategoryName: "Smart Watches",
    categoryId: 6,
    value: null,
    productId: null,
  },
  {
    name: "Color",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Men's Fashion",
    subCategoryName: "Pants",
    categoryId: 6,
    value: null,
    productId: null,
  },
  {
    name: "Color",
    filterType: "MULTIPLE_SELECT",
    categoryName: "Men's Fashion",
    subCategoryName: "Jackets",
    categoryId: 6,
    value: null,
    productId: null,
  },
];
